language: php

php:
    - 7.3
    - 7.4

matrix:
    fast_finish: true

    include:
        -   php: 7.3
            env: PREFER_LOWEST=1

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer require --dev dereuromark/composer-prefer-lowest; fi

script:
    - find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

    - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest || true; fi

cache:
    directories:
        - $HOME/.composer/cache/
